---
title: "Introduction"
---

Power plants can face operational constraints due to environmental conditions. These constraints can lead to plants being unable to meet demands and forcing decreased efficiency. One of the most impactful constraints is cooling because can cause emergency shutdown and equipment damage.A way this has been mitigated is by having a connected system to help compensate for local constraints of plants. This solution has been adopted by the Alabama Power Company, which operates 81 generating units and 26 facilities @generati.

It is unknown how often a power plant will have to run at a reduced capacity as well as the reduction requirements, while still being able to meet demands. The objective of this report is to assess the risk that the Dauphin Island power plant will have to run at reduced capacity as well as the total impact. This study analyzes the frequency of months that exceed 85°F and the generation at different reduced-capacity scenarios. This study will also project the next 5 years. 