---
title: "Methods"
---

## Water Temperature

We obtained a water temperature dataset[^methods-1] from the National Oceanic and Atmospheric Administration. The dataset had covered the hourly temperature observations from the years of 2020 to 2024 for the station in Dauphin Island @station. There were no available observations for the year of 2021, due to Hurricane Ida. This data was used to identify the likelihood of the water temperature exceeds the temperature threshold that the plant is able to handle (\> 85F) using a confidence interval of 95%. Monthly average temperatures and the proportion of days exceeding 85F were calculated. High and moderate risk were months where more 50% and 20% of days exceeded 85F, respectively. We had then projected the next 5 years, and identified, which months would need to be ran at reduced capacity. To do this we had ran a linear regression model to find the trend and follow the trend for the projection.

[^methods-1]: https://tidesandcurrents.noaa.gov/physocean.html?i d=8735180

## Power Requirements

We obtained a dataset[^methods-2] on consumption from the U.S. Energy Information Administration. The dataset includes the consumption sales, per month, from all power companies from the years of 2020 to 2024 @formeia. This dataset was used to find the consumption demands required by Alabama Power Company to meet demands (Megawatt hours).

[^methods-2]: https://www.eia.gov/electricity/data/eia861m/

We obtained a dataset[^methods-3] on generation from the U.S. Energy Information Administration. The dataset had covered net generation, per month, that the James M. Barry Electric Generating Plant from the years of 2020 to 2024 @electric. This dataset was used because Dauphin Island receives its power from the company Alabama Power Company, and this could be used to find the contribution a power plant would take @alabama. 

This data was used to find the capabilities of the Plant in the periods where we need to run at reduced capacity (Megawatt hours). We then compared this generation factored in with its contribution to consumption trends of Alabama Power Company. We defined reduced capacity as increments of 10%. These would be applied once temperature exceeds the applicable amount, the thresholds were starting at 85 and increased by 10% afterwards. We used the capacity type *Normal Capacity* as the real capacity used at the date. We are applying the assumption that the power plant does not need to go at a decreased capacity due to not being coastal, but was not found to be relevant because of Alabama Power Company being treated as a support system. We had predicted the impact over the next 5 years assuming that the rate of contribution stays consistent.

James M. Barry Electric Generating Plant was chosen because it produces the most out of the power plants under Alabama Power Company, to compensate for a power plant needing to contribute proportionately we increased the contribution rate of the power plant @generati.

[^methods-3]: https://www.eia.gov/beta/electricity/data/browser/#/plant/3?f req=M&start=202001&end=202512&ctype=linechart&ltype=pin&tab=generation&columnchart=ELEC.PLANT.GEN.3-ALL-ALL.M&maptype=0&pin=&linechart=
